// * Theme
// light: (
//     primary-5: var(--sendbird-primary-500),
// primary-4: var(--sendbird-primary-400),
// primary-3: var(--sendbird-primary-300),
// primary-2: var(--sendbird-primary-200), // didnt see usage yet
// primary-1: var(--sendbird-primary-100),
//
// // didnt see usage yet
// secondary-5: var(--sendbird-secondary-500),
// secondary-4: var(--sendbird-secondary-400),
// secondary-3: var(--sendbird-secondary-300),
// secondary-2: var(--sendbird-secondary-200),
// secondary-1: var(--sendbird-secondary-100),
//
// information-1: var(--sendbird-information-100),
// on-information-1: var(--sendbird-onlight-01),
//
// error-5: var(--sendbird-error-500),
// error-4: var(--sendbird-error-400),
// error-3: var(--sendbird-error-300),
// error-2: var(--sendbird-error-200),
// error-1: var(--sendbird-error-100),
//
// bg-8: var(--sendbird-primary-100),
// bg-7: var(--sendbird-background-700),
// bg-6: var(--sendbird-background-600),
// bg-5: var(--sendbird-background-500),
// bg-4: var(--sendbird-background-400),
// bg-3: var(--sendbird-background-300),
// bg-2: var(--sendbird-background-200),
// bg-1: var(--sendbird-background-100),
// bg-0: var(--sendbird-background-50),
//
// overlay-1: var(--sendbird-overlay-01),
// overlay-2: var(--sendbird-overlay-02),
//
// on-bg-1: var(--sendbird-onlight-01),
// on-bg-2: var(--sendbird-onlight-02),
// on-bg-3: var(--sendbird-onlight-03),
// on-bg-4: var(--sendbird-onlight-04),
//
// on-content-1: var(--sendbird-ondark-01),
// on-content-2: var(--sendbird-ondark-02),
// on-content-3: var(--sendbird-ondark-03),
// on-content-4: var(--sendbird-ondark-04),
// inverse-on-content-1: var(--sendbird-onlight-01),
// inverse-on-content-3: var(--sendbird-onlight-03),
//
// shadow-gradient-1: var(--sendbird-shadow-01),
// shadow-gradient-2: var(--sendbird-shadow-02),
// shadow-gradient-3: var(--sendbird-shadow-03),
// shadow-gradient-4: var(--sendbird-shadow-04),
// shadow-gradient-5: var(--sendbird-shadow-05),
//
// shadow-message-input: var(--sendbird-shadow-message-input),
// highlight--1: var(--sendbird-highlight-100),
// on-light-4: var(--sendbird-onlight-04),
//
// primary--1-4: var(--sendbird-primary-100),
// primary--1-7: var(--sendbird-primary-100),
// primary--3-2: var(--sendbird-primary-300),
//
// bg--0-0: var(--sendbird-background-50),
// bg--0-4: var(--sendbird-background-50),
// bg--0-5: var(--sendbird-background-50),
// bg--0-6: var(--sendbird-background-50),
// bg--1-5: var(--sendbird-background-100),
// bg--1-4: var(--sendbird-background-100),
// bg--1-3: var(--sendbird-background-100),
// bg--2-5: var(--sendbird-background-200),
// bg--2-7: var(--sendbird-background-200),
// bg--3-3: var(--sendbird-background-300),
// bg--7-3: var(--sendbird-background-700),
//
// primary--1-bg--7: var(--sendbird-primary-100),
// secondary--3-2: var(--sendbird-secondary-300),
// error--3-2: var(--sendbird-error-300),
// error--4-1: var(--sendbird-error-400),
// on-bg-4--bg-6: var(--sendbird-onlight-04),
// ),
// dark: (
//     primary-5: var(--sendbird-primary-400),
// primary-4: var(--sendbird-primary-300),
// primary-3: var(--sendbird-primary-200),
// primary-2: var(--sendbird-primary-400),
// primary-1: var(--sendbird-primary-300),
//
// secondary-5: var(--sendbird-secondary-500),
// secondary-4: var(--sendbird-secondary-400),
// secondary-3: var(--sendbird-secondary-200),
// secondary-2: var(--sendbird-secondary-200),
// secondary-1: var(--sendbird-secondary-100),
//
// information-1: var(--sendbird-information-100),
// on-information-1: var(--sendbird-onlight-01),
//
// error-5: var(--sendbird-error-500),
// error-4: var(--sendbird-error-400),
// error-3: var(--sendbird-error-300),
// error-2: var(--sendbird-error-200),
// error-1: var(--sendbird-error-100),
//
// bg-8: var(--sendbird-background-700),
// bg-7: var(--sendbird-background-50),
// bg-6: var(--sendbird-background-100),
// bg-5: var(--sendbird-background-200),
// bg-4: var(--sendbird-background-300),
// bg-3: var(--sendbird-background-400),
// bg-2: var(--sendbird-background-400),
// bg-1: var(--sendbird-background-500),
// bg-0: var(--sendbird-background-600),
//
// overlay-1: var(--sendbird-overlay-01),
// overlay-2: var(--sendbird-overlay-02),
//
// on-bg-1: var(--sendbird-ondark-01),
// on-bg-2: var(--sendbird-ondark-02),
// on-bg-3: var(--sendbird-ondark-03),
// on-bg-4: var(--sendbird-ondark-04),
//
// on-content-1: var(--sendbird-onlight-01),
// on-content-2: var(--sendbird-onlight-02),
// on-content-3: var(--sendbird-onlight-03),
// on-content-4: var(--sendbird-onlight-04),
// inverse-on-content-1: var(--sendbird-ondark-01),
// inverse-on-content-3: var(--sendbird-ondark-03),
//
// shadow-gradient-1: var(--sendbird-shadow-01),
// shadow-gradient-2: var(--sendbird-shadow-02),
// shadow-gradient-3: var(--sendbird-shadow-03),
// shadow-gradient-4: var(--sendbird-shadow-04),
// shadow-gradient-5: var(--sendbird-shadow-05),
//
// shadow-message-input: var(--sendbird-shadow-message-input),
// highlight--1: var(--sendbird-highlight-100),
//
// on-light-4: var(--sendbird-onlight-04),
//
// primary--1-4: var(--sendbird-primary-400),
// primary--1-7: var(--sendbird-background-700),
// primary--3-2: var(--sendbird-primary-200),
//
// bg--0-0: var(--sendbird-background-50),
// bg--0-4: var(--sendbird-background-400),
// bg--0-5: var(--sendbird-background-500),
// bg--0-6: var(--sendbird-background-600),
// bg--1-5: var(--sendbird-background-500),
// bg--1-4: var(--sendbird-background-400),
// bg--1-3: var(--sendbird-background-300),
// bg--2-5: var(--sendbird-background-500),
// bg--2-7: var(--sendbird-background-700),
// bg--3-3: var(--sendbird-background-300),
// bg--7-3: var(--sendbird-background-300),
//
// primary--1-bg--7: var(--sendbird-background-700),
// secondary--3-2: var(--sendbird-secondary-200),
// error--3-2: var(--sendbird-error-200),
// error--4-1: var(--sendbird-error-100),
// on-bg-4--bg-6: var(--sendbird-background-600),
// ),
