# builder
FROM node:18.17.1-alpine AS builder

WORKDIR /app
COPY ./packages/self-service ./

RUN npm install
RUN npm run build

# production
FROM nginx:1.25.4-alpine-slim
COPY --from=builder /app/dist /usr/share/nginx/html
