# builder
FROM node:18.17.1-alpine AS builder

WORKDIR /app
COPY ./packages/url-webdemo ./

ARG VITE_CHAT_WIDGET_APP_ID VITE_CHAT_WIDGET_BOT_ID \
    VITE_WEB_DEMO_APP_ID VITE_WIDGET_DEMO_APP_ID

ENV VITE_CHAT_WIDGET_APP_ID=$VITE_CHAT_WIDGET_APP_ID
ENV VITE_CHAT_WIDGET_BOT_ID=$VITE_CHAT_WIDGET_BOT_ID
ENV VITE_WEB_DEMO_APP_ID=$VITE_WEB_DEMO_APP_ID
ENV VITE_WIDGET_DEMO_APP_ID=$VITE_WIDGET_DEMO_APP_ID

RUN npm install
RUN npm run build

# production
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
