version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-s3: circleci/aws-s3@4.0.0
  
executors:
  ci-aws:
    docker:
      - image: cimg/aws:2024.03
    resource_class: small
  node:
    docker:
      - image: cimg/node:18.17.1
    resource_class: medium

commands:
  aws-create-invalidation:
    description: Create invalidation in CloudFront distribution
    parameters:
      distribution-id:
        default: default
        description: Distribution id for CloudFront
        type: string
      paths:
        default: /
        description: Target paths for invalidation
        type: string
      profile:
        default: default
        description: AWS profile name
        type: string
    steps:
      - run:
          command: |
            echo "Create invalidation in CloudFront"
            aws cloudfront create-invalidation \
                --distribution-id <<parameters.distribution-id>> \
                --paths <<parameters.paths>> --profile <<parameters.profile>>

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: install dependencies and build
          command: |
            cd ./packages/self-service
            npm install
            npm run build
      - persist_to_workspace:
          root: ./packages/self-service
          paths:
            - dist
  upload_to_s3_and_invalidate_cache:
    executor: ci-aws
    parameters:
      s3_bucket:
        type: string
      distribution_id:
        type: string
      role_arn:
        type: string
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
          configure-default-region: false
      - aws-cli/role-arn-setup:
          profile-name: ci-web
          source-profile: default
          role-arn: << parameters.role_arn >>
      - aws-s3/sync:
          from: dist/
          to: << parameters.s3_bucket >>
          profile_name: ci-web
      - aws-s3/copy:
          arguments: '--metadata-directive REPLACE --cache-control "max-age=0" --content-type application/javascript'
          from: << parameters.s3_bucket >>/index.js
          to: << parameters.s3_bucket >>/index.js
          profile_name: ci-web
      - aws-s3/copy:
          arguments: '--metadata-directive REPLACE --cache-control "max-age=86400" --content-type application/javascript --recursive'
          from: << parameters.s3_bucket >>/${CIRCLE_TAG}
          to: << parameters.s3_bucket >>/${CIRCLE_TAG}
          profile_name: ci-web
      - aws-create-invalidation:
          distribution-id: << parameters.distribution_id >>
          paths: '/index.js'
          profile: ci-web

workflows:
  deploy_to_s3:
    jobs:
      - build:
          name: build
          filters: &only_version_tag_trigger
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - upload_to_s3_and_invalidate_cache:
          name: upload_to_s3_and_invalidate_cache
          filters: *only_version_tag_trigger
          s3_bucket: $S3_BUCKET
          distribution_id: $DISTRIBUTION_ID
          role_arn: $ROLE_ARN
          requires:
            - build
          context:
            - circleci-dashboard-bot
      - build:
          name: build_staging
          filters: &only_version_tag_trigger_staging
            tags:
              only: /^v\d+\.\d+\.\d+-staging(\.\d+)?$/
            branches:
              ignore: /.*/
      - upload_to_s3_and_invalidate_cache:
          name: upload_to_s3_and_invalidate_cache_staging
          filters: *only_version_tag_trigger_staging
          s3_bucket: $S3_BUCKET_STAGING
          distribution_id: $DISTRIBUTION_ID_STAGING
          role_arn: $ROLE_ARN_STAGING
          requires:
            - build_staging
          context:
            - circleci-dashboard-bot
