version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.1.0
  aws-s3: circleci/aws-s3@4.0.0

executors:
  ci-aws:
    docker:
      - image: cimg/aws:2024.03
    resource_class: small
  node:
    docker:
      - image: cimg/node:20.13.1
    resource_class: medium

commands:
  aws-create-invalidation:
    description: Create invalidation in CloudFront distribution
    parameters:
      distribution-id:
        default: default
        description: Distribution id for CloudFront
        type: string
      paths:
        default: /
        description: Target paths for invalidation
        type: string
      profile:
        default: default
        description: AWS profile name
        type: string
    steps:
      - run:
          command: |
            echo "Create invalidation in CloudFront"
            aws cloudfront create-invalidation \
                --distribution-id <<parameters.distribution-id>> \
                --paths <<parameters.paths>> --profile <<parameters.profile>>

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: Enable Corepack
          command: corepack enable --install-directory ~/bin
      - run:
          name: install dependencies and build
          command: |
            cd ./packages/self-service
            yarn install --immutable --immutable-cache
            yarn build
      - persist_to_workspace:
          root: ./packages/self-service
          paths:
            - dist
  upload_to_s3_and_invalidate_cache:
    executor: ci-aws
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
          configure-default-region: false
      - aws-cli/role-arn-setup:
          profile-name: ci-web-prod
          source-profile: default
          role-arn: $DASHBOARD_CI_ROLE_ARN
      - aws-s3/sync:
          from: dist/
          to: $S3_BUCKET
          profile_name: ci-web-prod
      - aws-s3/copy:
          arguments: '--metadata-directive REPLACE --cache-control "max-age=0" --content-type application/javascript'
          from: $S3_BUCKET/index.js
          to: $S3_BUCKET/index.js
          profile_name: ci-web-prod
      - aws-s3/copy:
          arguments: '--metadata-directive REPLACE --cache-control "max-age=86400" --content-type application/javascript --recursive'
          from: $S3_BUCKET/${CIRCLE_TAG}
          to: $S3_BUCKET/${CIRCLE_TAG}
          profile_name: ci-web-prod
      - aws-create-invalidation:
          distribution-id: $DISTRIBUTION_ID
          paths: '/index.js'
          profile: ci-web-prod

workflows:
  deploy_to_s3:
    jobs:
      - build:
          name: build
          filters: &only_version_tag_trigger
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - upload_to_s3_and_invalidate_cache:
          name: upload_to_s3_and_invalidate_cache
          filters: *only_version_tag_trigger
          requires:
            - build
          context:
            - circleci-dashboard-bot
