name: PR comment bot
on:
  issue_comment:
    types: [created]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # see list of commands: https://github.com/sendbird/release-automation-action#commands
      - uses: sendbird/release-automation-action@latest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          circleci_token: ${{ secrets.CIRCLECI_API_TOKEN }}
          product: 'chat-ai-widget'
          platform: 'js'
          framework: 'react'
          product_jira_project_key: 'AC'
          product_jira_version_prefix: 'js_chat_ai_widget'
          changelog_file: 'CHANGELOG.md'
