name: PR size diff

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: "./dist/**/*.{js,css}"
          exclude: "{**/*.d.ts,**/node_modules/**}"
          strip-hash: "__bundle-\\d+-([a-zA-Z0-9_-]{8})\\.js$"
